/*
 * generated by Xtext 2.10.0
 */
package de.tu_bs.cs.isf.mbse.egg


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EggScriptionRuntimeModule extends AbstractEggScriptionRuntimeModule {
}
