/*
 * generated by Xtext 2.10.0
 */
package de.tu_bs.cs.isf.mbse.egg


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EggScriptionStandaloneSetup extends EggScriptionStandaloneSetupGenerated {

	def static void doSetup() {
		new EggScriptionStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
