<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="egglanguage" nsURI="https://www.tu-bs.de/cs/isf/mbse/egg" nsPrefix="egglanguage">
  <eClassifiers xsi:type="ecore:EClass" name="DescriptionRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptions" upperBound="-1"
        eType="#//Description" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Description" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pictures" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="animationDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="gui" nsURI="https://www.tu-bs.de/cs/isf/mbse/egg/gui" nsPrefix="gui">
    <eClassifiers xsi:type="ecore:EClass" name="Page" eSuperTypes="#//Description">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MenuPage" eSuperTypes="#//gui/Page"/>
    <eClassifiers xsi:type="ecore:EClass" name="TextPage" eSuperTypes="#//gui/Page">
      <eStructuralFeatures xsi:type="ecore:EReference" name="nextPage" lowerBound="1"
          eType="#//gui/Page"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Level" eSuperTypes="#//gui/Page">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gravity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="gameelements" nsURI="https://www.tu-bs.de/cs/isf/mbse/egg/gameelements"
      nsPrefix="gameelements">
    <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//Description">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="destroyable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="movable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasCollision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Item" eSuperTypes="#//Description"/>
    <eClassifiers xsi:type="ecore:EClass" name="Character" eSuperTypes="#//Description">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="jumpPower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startItems" upperBound="-1"
          eType="#//gameelements/Item"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hero" eSuperTypes="#//gameelements/Character"/>
    <eClassifiers xsi:type="ecore:EClass" name="Enemy" eSuperTypes="#//gameelements/Character"/>
  </eSubpackages>
</ecore:EPackage>
