<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="level" nsURI="https://www.tu-bs.de/cs/isf/mbse/egg/level" nsPrefix="level">
  <eClassifiers xsi:type="ecore:EClass" name="Level" eSuperTypes="descriptions.ecore#//Description">
    <eOperations name="getElement" eType="#//PlacedElement">
      <eParameters name="positionX" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="positionY" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="addElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="element" lowerBound="1" eType="#//PlacedElement"/>
    </eOperations>
    <eOperations name="removeElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="element" eType="#//PlacedElement"/>
    </eOperations>
    <eOperations name="removeElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="positionX" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="positionY" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="4"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="4"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gravity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="75"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ColumnEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RowEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//PlacedElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//RowEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlacedElement" abstract="true" eSuperTypes="commons.ecore#//PositionedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PlacedBlock" eSuperTypes="#//PlacedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="1"
        eType="ecore:EClass descriptions.ecore#//gameelements/BlockDescription"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlacedHero" eSuperTypes="#//PlacedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="1"
        eType="ecore:EClass descriptions.ecore#//gameelements/HeroDescription"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlacedItem" eSuperTypes="#//PlacedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="1"
        eType="ecore:EClass descriptions.ecore#//gameelements/ItemDescription"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlacedEnemy" eSuperTypes="#//PlacedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="1"
        eType="ecore:EClass descriptions.ecore#//gameelements/EnemyDescription"/>
  </eClassifiers>
</ecore:EPackage>
